r""" Implementation of the ProteinContext class containing the configuration for PDB/protein validation."""

_default_glide_context: "[ProteinContext]" = None

CRYSTAL_ADDITIVES = [
    "2PE",
    "EDO",
    "DMS",
    "CLF",
    "AZI",
    "SE4",
    "TRS",
    "IPA",
    "BAT",
    "MOH",
    "DTX",
    "HEC",
    "PT4",
    "DTP",
    "UNX",
    "OCY",
    "BET",
    "AKG",
    "ASO",
    "HPP",
    "FMT",
    "PCA",
    "LPE",
    "POV",
    "SIA",
    "ACT",
    "KCC",
    "BES",
    "THC",
    "2HP",
    "PEB",
    "1PE",
    "HYP",
    "NO3",
    "OLC",
    "CSP",
    "BOG",
    "PEC",
    "SAD",
    "HAR",
    "OLA",
    "PGE",
    "NET",
    "SEC",
    "OXL",
    "TYS",
    "BF4",
    "IEP",
    "LMT",
    "Y01",
    "CDL",
    "ERM",
    "CAS",
    "MLZ",
    "BB2",
    "PGO",
    "APC",
    "TLA",
    "TRI",
    "TBU",
    "BR0",
    "PC1",
    "SCH",
    "TEG",
    "EMT",
    "IMD",
    "N3",
    "AU1",
    "EHP",
    "PF5",
    "NH2",
    "SUL",
    "IPO",
    "NLE",
    "IZA",
    "CL7",
    "NAO",
    "IBM",
    "SGN",
    "IDS",
    "PLX",
    "ZNO",
    "SC2",
    "CSW",
    "PX4",
    "ASX",
    "VO4",
    "HAC",
    "DGD",
    "RGD",
    "STY",
    "NME",
    "SVX",
    "REO",
    "ICD",
    "AU3",
    "BCL",
    "MLY",
    "F15",
    "FGA",
    "AG1",
    "TAR",
    "PHI",
    "CUB",
    "STU",
    "CU1",
    "1ZN",
    "PO2",
    "C8E",
    "HNE",
    "DAM",
    "HC4",
    "PYL",
    "LFA",
    "CHL",
    "3PE",
    "MVA",
    "HLU",
    "ACN",
    "VPO",
    "F3S",
    "YCM",
    "CPS",
    "FUL",
    "3BV",
    "CAC",
    "CSD",
    "PTY",
    "CSO",
    "EPE",
    "PTR",
    "CYN",
    "FME",
    "WCC",
    "PO3",
    "HSE",
    "PLM",
    "THX",
    "CLA",
    "MPD",
    "PEG",
    "DTT",
    "BME",
    "GOL",
    "OCS",
    "PAM",
    "ACY",
    "ZN3",
    "HG2",
    "NO2",
    "CUA",
    "LCO",
    "CSX",
    "GNP",
    "PG4",
    "Z99",
    "UNL",
    "S2M",
    "FLC",
    "NAP",
    "DTT",
    "BMA",
    "B3P",
    "NCO",
    "5IU",
    "PRT",
    "PRP",
    "SO4",
    "P5S",
    "IAS",
    "MLI",
    "CUZ",
    "NH4",
    "MRD",
    "MNO",
    "OGA",
    "WO4",
    "EDA",
    "CUW",
    "ANP",
    "HCS",
    "CYM",
    "DSN",
    "BEN",
    "APR",
    "SER",
    "MES",
    "H5M",
    "HG1",
    "AG2",
    "H2B",
    "SCN",
    "ALF",
    "NLN",
    "SAR",
    "PDV",
    "EOH",
    "DMF",
    "OHX",
    "IOD",
    "PPM",
    "CRF",
    "ORN",
    "PEE",
    "MAN",
    "CO3",
    "CL0",
    "PCW",
    "XAN",
    "SF4",
    "ACB",
    "YT3",
    "XO4",
    "M3L",
    "ALY",
    "PG5",
]

COFACTORS = [
    "HEM",
    "HC3",
    "MSE",
    "ACO",
    "VAN",
    "SAM",
    "ADP",
    "GLU",
    "ASP",
    "GLN",
    "LYS",
    "NDG",
    "URA",
    "DAL",
    "FE3",
    "FE2",
    "AMP",
    "FMN",
    "ZN1",
    "GDP",
    "HEA",
    "GLY",
    "CD2",
    "NAD",
    "FAD",
    "COA",
    "PHE",
    "PRO",
    "HGB",
    "HCO",
    "NI2",
    "TYR",
    "PLP",
    "GAL",
    "MET",
    "PO4",
    "ATP",
    "ALA",
    "FUC",
    "LEU",
    "UDP",
    "FES",
    "WAT",
    "NAD",
    "HIS",
    "GTP",
    "COA",
    "VAL",
    "G6D",
    "CME",
    "SAH",
    "MLY",
    "NAI",
    "ACE",
    "GLC",
    "TPO",
    "MLI",
]


# pylint: disable-next=too-many-instance-attributes
class ProteinContext:
    r"""Singleton for protein pdb structures validation"""

    # pylint: disable-next=too-many-arguments,too-many-locals
    def __init__(
        self,
        impurities: list | None = None,
        cofactors: list | None = None,
        crystal_additives: list | None = None,
    ):
        r"""Initialize the ProteinContext class with the given impurities, cofactors and crystal_additives."""
        self.cofactors = cofactors if cofactors is not None else COFACTORS.copy()
        self.crystal_additives = (
            crystal_additives
            if crystal_additives is not None
            else CRYSTAL_ADDITIVES.copy()
        )
        self.impurities = (
            impurities if impurities is not None else COFACTORS + CRYSTAL_ADDITIVES
        )

    @staticmethod
    def get_current() -> "ProteinContext":
        r"""Get or create a singleton context."""

        # pylint: disable-next=global-statement
        global _default_glide_context

        if _default_glide_context is None:
            _default_glide_context = ProteinContext(
                impurities=COFACTORS + CRYSTAL_ADDITIVES,
                cofactors=COFACTORS,
                crystal_additives=CRYSTAL_ADDITIVES,
            )
        return _default_glide_context

    @staticmethod
    def set_current(context: "ProteinContext") -> None:
        """Set the current context."""
        global _default_glide_context
        _default_glide_context = context
