[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "lignova"
version = "0.0.0"
description = "LIGNOVA: An automated pipeline to generate high-quality docked protein–ligand complexes at scale"
authors = [
    {name = "Mayar Ahmed", email = "mma121@pitt.edu"},
    {name = "Alex M. Maldonado", email = "alex.maldonado@pitt.edu"},
    {name = "Jacob D. Durrant", email = "durrantj@pitt.edu"},
]
maintainers = [
    {name = "Durrant Lab", email = "durrantj@pitt.edu"},
]
requires-python = ">=3.11,<3.13"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE.md", "NOTICE", "THIRD_PARTY_LICENSES.md", "AUTHORS"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "h5py>=3.15.1,<4",
    "numpy>=2.4.2,<3",
    "rdkit>=2025.9.5,<2026",
    "loguru>=0.7.3,<0.8",
    "mdanalysis>=2.10.0,<3",
    "pandas>=3.0.1,<4",
    "scipy>=1.17.1,<2",
    "spyrmsd>=0.9.0,<0.10",
    "gemmi>=0.7.5,<0.8",
    "fasteners>=0.19,<0.20",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["lignova*"]
