[project]
name = "lignova"
version = "0.0.0"
description = "TODO"
authors = [
    {name = "Durrant Lab", email = "durrantj@pitt.edu"},
]
requires-python = ">=3.11,<3.13"
readme = "README.md"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "h5py>=3.12.1,<4",
    "numpy>=1.26.0,<3",
    "rdkit>=2024.9.2,<2026",
    "loguru>=0.7.2,<0.8",
    "mdanalysis>=2.1.0,<3",
    "pandas>=2.2.3,<3",
    "scipy>=1.14.1,<2",
    "spyrmsd>=0.8.0,<1.0",
    "gemmi>=0.6.4,<1.0",
    "fasteners>=0.17.3,<1.0",
]

[build-system]
requires = ["setuptools"]

[tool.setuptools.packages.find]
where = ["lignova"]
