#!/bin/bash
#SBATCH --job-name=prep_prot
#SBATCH --array=38
#SBATCH --nodes=1
#SBATCH --mem=8G
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --time=10:00:00
#SBATCH --cluster=htc
#SBATCH --partition=preempt
#SBATCH --output=../logs/prot_prep/%x_%A_%a.out
#SBATCH --error=../logs/prot_prep/%x_%A_%a.err

# environment setup
set -euo pipefail 
pwd
module purge
mkdir -p ../logs/prot_prep

# user-configurable paths
PARQUET="../../lignova_parquets/final_ligand_cluster_0.7_Tc.parquet"
INPUT_DIR="../raw"              # raw_protein-ligand_structures
OUTDIR="../prepared_prot"        # prepared_proteins, protonated_proteins
CONFIG_YAML="../prepared_prot/pdb2pqr.yaml"    # have to give a path even if it doesn't exist yet
PDBQT_PATH="../prepared_prot/pdbqt_conversion.yaml"  # have to give a path even if it doesn't exist yet
BATCH_SIZE=50


if [[ -f "${CONFIG_YAML}" ]]; then
    echo "pdb2pqr config: USER (${CONFIG_YAML})"
else
    echo "pdb2pqr config: DEFAULTS (${CONFIG_YAML} not found)"
fi
if [[ -f "${PDBQT_PATH}" ]]; then
    echo "pdbqt conversion config: USER (${PDBQT_PATH})"
else
    echo "pdbqt conversion config: DEFAULTS (${PDBQT_PATH} not found)"
fi


# compute range for this array task
TASK_ID=${SLURM_ARRAY_TASK_ID}
START_IDX=$(( TASK_ID * BATCH_SIZE ))
END_IDX=$(( START_IDX + BATCH_SIZE ))

echo "Array task ${TASK_ID}: processing indices [${START_IDX}, ${END_IDX})"
echo "Job ID:       ${SLURM_JOB_ID:-N/A}"
echo "Array Task:   ${SLURM_ARRAY_TASK_ID:-N/A}"
echo "Node:         $(hostname)"
echo "Started at:   $(date)"
echo "Working dir:  $(pwd)"
echo "Using pdb2pqr config:  ${CONFIG_YAML}"
echo "Using pdbqt conversion config: ${PDBQT_PATH}"

#run data prep for this batch
pixi run python3 -m run_scripts.data_prep \
        -m protein \
        -i ${INPUT_DIR} \
        -p ${PARQUET} \
        -o ${OUTDIR} \
        --start-index "${START_IDX}" \
        --end-index "${END_IDX}"

# Get the txt file generated by data_prep.py
TXT_LIST="${OUTDIR}/cleaned_pdblist_${START_IDX}_${END_IDX}.txt"	
echo "Expecting cleaned list: ${TXT_LIST}"
if [[ ! -f "${TXT_LIST}" ]]; then	
    echo "ERROR: cleaned list file not found: ${TXT_LIST}" >&2
    exit 1	
fi
mapfile -t CLEANED_FILES < "${TXT_LIST}"
echo "Got ${#CLEANED_FILES[@]} cleaned PDBs from data_prep.py"

if (( ${#CLEANED_FILES[@]} == 0 )); then
    echo "No cleaned PDBs listed; nothing to protonate. Exiting."
    exit 0
fi

PREPPED_BASE="${OUTDIR}"
PROTONATED_BASE="${OUTDIR}"
#protonate each cleaned pdb 
for CLEANED in "${CLEANED_FILES[@]}"; do
    echo "Protonating: ${CLEANED}"

    BASE_NAME=$(basename "${CLEANED}" .pdb)
    PDB_ID=$(echo "${BASE_NAME}" | tr '[:lower:]' '[:upper:]')

    OUT_DIR="${PROTONATED_BASE}/${PDB_ID}"
    mkdir -p "${OUT_DIR}"
    OUT_PATH="${OUT_DIR}/${BASE_NAME}_protonated.pqr"

    PROT_PDBQT_PATH="${OUT_DIR}/${BASE_NAME}_conversion_${SLURM_JOB_ID:-local}.yaml"
    PROT_CONFIG_YAML="${OUT_DIR}/${BASE_NAME}_pdb2pqr_${SLURM_JOB_ID:-local}.yaml"

    if [[ -f "${PDBQT_PATH}" ]]; then
        cp "${PDBQT_PATH}" "${PROT_PDBQT_PATH}"
    fi
    if [[ -f "${CONFIG_YAML}" ]]; then
        cp "${CONFIG_YAML}" "${PROT_CONFIG_YAML}"
    fi

    # Attempt protonation and skip to the next file if it fails
    if ! pixi run python3 -m run_scripts.protonate \
        -p "${CLEANED}" \
        -c "${PROT_CONFIG_YAML}" \
        -o "${OUT_PATH}" \
        -m mgltools \
        -pq "${PROT_PDBQT_PATH}"; then
        echo "WARNING: Protonation failed for ${CLEANED}. Skipping to the next file." >&2
        continue
    fi
done

echo "All protonation done for array task ${TASK_ID}."
echo "Finished at: $(date)"
